# Generated by Django 2.2.9 on 2020-01-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpdb_api', '0007_userrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrating',
            options={'ordering': ['-created']},
        ),
    ]
