# Generated by Django 2.2.9 on 2020-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpdb_api', '0008_auto_20200115_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='average_rating',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
