# Generated by Django 2.2.9 on 2020-01-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpdb_api', '0009_userrating_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='average_rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
