# Generated by Django 2.2.9 on 2020-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpdb_api', '0010_auto_20200121_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
