# Generated by Django 2.2.9 on 2020-01-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpdb_api', '0005_auto_20191224_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-created']},
        ),
    ]
