# Generated by Django 2.2.9 on 2020-01-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpdb_api', '0011_auto_20200121_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='average_rating',
        ),
    ]
